name: Send Daily Exchange Rates and Weather

on:
  schedule:
    # Har kuni Toshkent vaqti bilan soat 10:00 da (UTC 05:00) ishlaydi
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  send-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
