name: Send Daily Exchange Rates

on:
  schedule:
    # Har kuni Toshkent vaqti bilan 09:00 da (UTC 04:00) ishlaydi
    - cron: '0 4 * * *'
  workflow_dispatch: # GitHub'da tugmani bosib qo'lda ham yuborish imkoni

jobs:
  send-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
